### ISSUE TITLE
creation of vocab

### ISSUE THREAD

**Issue by BerndStromberg** [dbmdz/berts#1]
Hey guys,

great to see another public BERT model for german 👍 

Could you say sth. about how you managed to handle the 16GB text data in SentencePiece for vocab creation? I get "bad_alloc" all the time when I'm trying to process all of my data. I am aware of `VOC_SIZE, INPUT_SENTENCE_SIZE, SHUFFLE_INPUT_SENTENCE,` etc. but still ... I don't want to use a subset of my data. What's your approach?

**Comment by stefan-it** [comment]
Hi @BerndStromberg,

we also used a subset of the corpus for generating the sentence piece vocab. To be more precisely, we follow the sciBERT steps for generating the (bpe) [vocab](https://github.com/allenai/scibert/blob/master/scripts/cheatsheet.txt#L6) and used 100,000,000 random sentences. 

I think this approach is very common, e.g. XLNet is also using a subset for creating the vocab :)

**Comment by stefan-it** [comment]
You could also try the `fastBPE` implementation from Lample:

https://github.com/glample/fastBPE

Maybe with that implementation it is possible to use larger files 🤔

**Comment by BerndStromberg** [comment]
Thanks for responding so fast 😄 

I've only tried unigram because it is the default. I'll definitely do another run with bpe mode or fastBPE lib. Feedback coming soon :)

**Comment by BerndStromberg** [comment]
Hey @stefan-it ,

today I tried to handle ca. _50 million sentences_ but still ... crash (no matter if `unigram` or `bpe`). Next try was based on ca. _24 million sentences_ ... crashed. It's always the same: `trainer_interface.cc(114) LOG(WARNING) Too many sentences are loaded! (24366057), which may slow down training.`

And now I am even more confused because you are talking about _100 mio. sentences_ as input 😮. So I got a few more questions:
- How much RAM do you got?
- What are your input params for `spm_train` ?
- Raw sentences without ANY preprocessing?
- `spm_train `with c++ or with Python Wrapper?

**Comment by stefan-it** [comment]
I was using the Python interface (not the `spm_train` command):

```python
import sentencepiece as spm 
spm.SentencePieceTrainer.Train('--input=corpus.txt --model_prefix=bpe-german --vocab_size=31000 --character_coverage=0.9999 --model_type=bpe --input_sentence_size=100000000 --shuffle_input_sentence=true')
```

This will approx. use 80GB of RAM. I did no specific pre-processing, except sentence splitting with `spacy` :)

**Comment by stefan-it** [comment]
Will close the issue for now. If you have further questions, please feel free to re-open it :)
