### ISSUE TITLE
Release TF Model for BERTurk for TF-only environments

### ISSUE THREAD

**Issue by monatis** [dbmdz/berts#10]
Hi, thanks a lot for releasing Turkish BERT model --your work is just amazing. I'm raising this issue per your statement [here](https://huggingface.co/dbmdz/bert-base-turkish-cased). This is especially needed in TF-only environments: Rasa is one such example. in `HFTransformersNLP` component added in v1.8, we can now use Rasa with HuggingFace Transformers model. As I read from [Rasa source code here](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/utils/hugging_face/registry.py), they load weights specifically with `TFBertModel` class, which is expectedly unable to load a missing `tf_model.h5` in `dbmdz/bert-base-turkish-cased`. I tried to update Rasa source code to use `AutoTokenizer` and `AutoModel`; however, it seems that it might require a breaking change in several core features in Rasa. I think that a TF model might also be useful in other TF-only environments. So, is it possible that you release it? I can willingly and happily collaborate on this if help is needed.

**Comment by stefan-it** [comment]
Hi @monatis ,

thanks for interest in the BERTurk model.

Model conversion to a TF-compatible H5 format is on my todo list! I got some TF error messages when I tried it the last time, but I hope that it is working this time 😅

**Comment by monatis** [comment]
Great news. Looking forwat to it! 😊

**Comment by stefan-it** [comment]
Hi @monatis ,

I've uploaded a TF-compatible model - you can now use it with:

```python
from transformers import  TFBertModel
model = TFBertModel.from_pretrained('dbmdz/bert-base-turkish-cased')
```

Please let me know, if that works for you!

**Comment by monatis** [comment]
Hi @stefan-it, I tested it with a basic chat bot powered by Rasa, and it works like a charm (planning to release a sample app like this). I also shared the news [on the Twitter acount of TensorFlow Turkey](https://twitter.com/TensorFlowTurk/status/1249771339822628864), the TF community I'm leading. Thanks a lot for your efforts and support for the open-source.

**Comment by sahinbatmaz** [comment]
This is just great. Thank you for easy to use Turkish Bert model. It is provided with transformers package, and there are pytorch and tf versions of it. Also there are cased/uncased/128k_vocab versions of it. Thanks 👍 👍
