### ISSUE TITLE
German BERT on older pytorch-transformers

### ISSUE THREAD

**Issue by yv** [dbmdz/berts#11]
Hi, we're using the deepset BERT model together with AllenNLP 0.9.0 (i.e. the older Pytorch-transformers library). Is there an easy way to make the dbmdz models (cased & uncased) usable in that environment? A non-easy way would also do. Thanks a lot!

**Comment by stefan-it** [comment]
Hi @yv ,

I think one way should be to download the model, configuration file and vocab and use this path name in deepset.

E.g.:

```bash
mkdir -p /tmp/bert-base-german-dbmdz-cased && cd $_

wget https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-base-german-cased/config.json
wget https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-base-german-cased/pytorch_model.bin
wget https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-base-german-cased/vocab.txt
```

Then use `/tmp/bert-base-german-dbmdz-cased` as model name in your library. I think in previous versions of Transformers (`pytorch-transformers` or even `pytorch-pretrained-bert`) the configuration file was named `bert_config.json`, but you'll see it in the error message then :)

Please let me know, if that's working for you!

**Comment by yv** [comment]
Hi @stefan-it ,
that's what worked for me in the end - you need to download the files to a common directory and use the unprefixed filenames (`pytorch_model.bin` instead of `bert-base-german-dbmdz-cased-pytorch_model.bin`, similarly for `config.json` and `vocab.txt`), and then use the directory as model name. Thanks for the quick reply!
