### ISSUE TITLE
Text Corpus to train and Open Source RoBERTa Model

### ISSUE THREAD

**Issue by PhilipMay** [dbmdz/berts#14]
Hi,
I did read about your german BERT model at hugging faces. I would like to train an RoBERTa model.
Since I also want to give the work back as open source to the community and could reference you:

Is it possible to use your german text corpus? You write:

> recent Wikipedia dump, EU Bookshop corpus, Open Subtitles, CommonCrawl, ParaCrawl and News Crawl. This results in a dataset with a size of 16GB and 2,350,234,427 tokens.

**Comment by stefan-it** [comment]
Links are out 😅 Please re-open if you have further questions :)
