### ISSUE TITLE
Tensorflow checkpoint for Italian BERT

### ISSUE THREAD

**Issue by federicoruggeri** [dbmdz/berts#15]
Hello there,
First of all, thank you very much for your awesome work! Such repositories are of great help.
I was wondering if it is possible to have access to tensorflow checkpoints for the italian pre-trained version of BERT (or if there's already some available).  I'm currently looking for a good pre-trained italian model for research.

Thanks in advance!
Best,
Federico

**Comment by stefan-it** [comment]
Hi @federicoruggeri ,

no problem, you can download the checkpoints here:

```bash
$ wget https://schweter.eu/cloud/berts/bert-base-italian-xxl-cased.tar.gz
$ wget https://schweter.eu/cloud/berts/bert-base-italian-xxl-uncased.tar.gz
```

Btw: I'm planing to release an ELECTRA model very soon for Italian :)

**Comment by stefan-it** [comment]
Model checkpoints are availabe (see link below), and also released the mentioned ELECTRA models, see [this repository](https://github.com/stefan-it/italian-bertelectra) for more information!

So I'm closing the issue for now :)
