### ISSUE TITLE
Bert for QA task

### ISSUE THREAD

**Issue by luke4u** [dbmdz/berts#18]
Hi there, 

First, thanks for making and sharing these German Bert models. 

I am wondering if possible to fine-tune the models on question answering tasks? If so, what is the procedure to follow? 

Thanks in advance.

**Comment by stefan-it** [comment]
Hi @luke4u ,

whenever the dataset is in a SQuAD compatible format, then you can use the example code in Transformers library, see:

https://github.com/huggingface/transformers/tree/master/examples/question-answering

As I've seen the same issue in the FARM repository, let's discuss it there :)

https://github.com/deepset-ai/FARM/issues/475

**Comment by luke4u** [comment]
Thank you @stefan-it .
