### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by LRParser** [dbmdz/berts#19]
Can you please clarify the license for these models?

**Comment by stefan-it** [comment]
Hi @LRParser ,

the license is MIT - I did specify it on the Hugging Face model hub, but unfortunately, it is not mentioned in the repo here 😅

I will add an extra section now!

**Comment by LRParser** [comment]
Thanks!

**Comment by stefan-it** [comment]
Was added to main readme now, so I'm closing here :hugs:
