### ISSUE TITLE
Potential publishing of TF checkpoints

### ISSUE THREAD

**Issue by wittenator** [dbmdz/berts#2]
Awesome work in creating another German BERT model trained on rather scientific texts, dbmdz team!
I would like to use your model with [Bert-as-Service](https://github.com/hanxiao/bert-as-service) and would need the TF checkpoints for that. Do you have them somewhere laying around by any chance?

**Comment by stefan-it** [comment]
Hi @wittenator,

thanks for your interest!

The original TF checkpoints can be downloaded via:

```bash
wget https://schweter.eu/cloud/berts/bert-base-german-dbmdz-cased.tar.gz # cased model
wget https://schweter.eu/cloud/berts/bert-base-german-dbmdz-uncased.tar.gz # uncased model
```

Please let me know if that worked for you!

**Comment by wittenator** [comment]
Sorry for the hefty delay. The checkpoints work like a charm, thanks a lot for this!
Out of curiosity, how hard would it be further train the model on more data? By chance I have a text dump of DFGs GEPRIS database at hand which could be useful for this.

**Comment by PaprikaSteiger** [comment]
Hey you two @wittenator , @stefan-it 

First of all, thank you for this model.

I'm kind of new to tensorflow, pytorch, checkpoints and so on, though I have some basic experience working with keras. 
I'd like to use this German BERT model as a language model and add some keras layers on top of it to use it for Sentiment Analysis. 

I'm following this tutorial:
 https://towardsdatascience.com/fine-tuning-bert-with-keras-and-tf-module-ed24ea91cff2

 Using the code provided here:
https://github.com/gaphex/bert_experimental/tree/master/finetuning

It provides a BertLayer class to wrap a pre-trained BERT model. 
This part of the code exports the model via tensorflow_hub using the vocab, configure und checkpoint file, the export is then passed to the BertLayer.

    module_fn = build_module_fn(config_path, vocab_path)
    spec = hub.create_module_spec(module_fn, tags_and_args=tags_and_args)
    spec.export("bert-module",
                checkpoint_path= *checkpoint path here*

My question is, downloading the checkpoints I end up with those three files, but I don't know what to pass as checkpoint_path. Do I have to merge these three files somehow? 

> model.ckpt.data-00000-of-00001
> model.ckpt.index
> model.ckpt.meta

Thank you for your help

**Comment by stefan-it** [comment]
Hi @wittenator ,

we haven't use your recommended corpus for future models, but we recently released larger models for German, see our paper:

[German’s Next Language Model](https://www.aclweb.org/anthology/2020.coling-main.598/)

(Colab with @brandenchan and @Timoeller from [deepset](https://github.com/deepset-ai).

So feel free to try our new models :hugs:
