### ISSUE TITLE
Turkish BERT Uncased Checkpoints

### ISSUE THREAD

**Issue by feyzazeynep** [dbmdz/berts#29]
Hi.

Could you please release checkpoints for 'bert-base-turkish-128k-uncased' ?

**Comment by stefan-it** [comment]
Hi @feyzazeynep ,

you can find the TensorFlow checkpoints (both cased and uncased) for the models with 128k here:

https://github.com/stefan-it/turkish-bert/issues/1#issuecomment-619624964

:)

**Comment by feyzazeynep** [comment]
Thank you so much @stefan-it  :)
