### ISSUE TITLE
Tensorflow weights for bert-base-italian-cased

### ISSUE THREAD

**Issue by gerzin** [dbmdz/berts#36]
Hello, I'm raising this issue in order to ask if it is possible to get the weights of bert-base-italian-cased for Tensorflow.

**Comment by stefan-it** [comment]
Hi @gerzin ,

are the checkpoints of the XXL version also suffient for your task:

https://github.com/dbmdz/berts/issues/15#issuecomment-648771155

Usually, the XXL version is much better than the "normal" model :hugs:

**Comment by gerzin** [comment]
Oh, my mistake, I already meant the XXL version. Thank you very much for all your work :)
