### ISSUE TITLE
bert-ita-xxl-cased training set

### ISSUE THREAD

**Issue by IreneSucameli** [dbmdz/berts#41]
Hi, I don't quite get how large is the training set of bert-ita-xxl-cased.
In the Hugging-face page is reported as size of the "training corpus" 13B tokens; is that the size of the set or of the entire dataset used?
Thanks

**Comment by stefan-it** [comment]
Hi @IreneSucameli , it is the total size of the training dataset, which consists of the OPUS files (used for training the non-XXL version, which is 13GB) and OSCAR 2019 (68GB), so the total training corpus has a size of 81GB :hugs:

**Comment by IreneSucameli** [comment]
I see, thanks a lot for your quick reply!
