### ISSUE TITLE
How to use italian models with TFBertModel - (headless)?

### ISSUE THREAD

**Issue by wtfzambo** [dbmdz/berts#5]
Hello,
for starters thanks for creating the Italian models.

I'm pretty new to the whole transformers / bert architecture so forgive me if this question is dumb. Anyway, I have a dataset upon which I'm trying to do a classification based on NLP (multi-class). Each row is a sentence of variable length + the target class in a separated attribute.

I started by using:
```python
TFBertModel.from_pretrained('bert-base-multilingual-cased')
```

Since I wasn't entirely happy, I tried changing the argument from multilingual to the dbmdz italian one, but received this error:
```python
AssertionError: Error retrieving file /root/.cache/torch/transformers/076c0d3e6f9148ae7c8bc48e2818d4ff03ec5bc68115b361cfa8b1795b4c9683.h5
```

I had also tried using `AutoModel`, but that doesn't seem to fit my case as it's not headless.

Any suggestion is gonna be much appreciated.

**Comment by stefan-it** [comment]
Hi  @wtfzambo ,

thanks for your interest in our model 🤗

I'm pretty sure you got this error message, because we currently have not uploaded TF compatible weights.

I'll convert the models into the required TF format very soon and ping you whenever the models are uploaded to the Hugging Face model hub!

**Comment by wtfzambo** [comment]
Amazing thanks!

Just out of curiosity, so that I can better understand:

what's the difference between `TFBertModel` headless and the other ones with heads for which your model works? Besides the fact that TF is headless of course.

I'm still pretty darn confused about this whole bert thing and getting on track feels very exhausting

**Comment by stefan-it** [comment]
Hi @wtfzambo ,

sorry for the long reponse time! The Italian model is now available in a TF-compatible format. If you want to use it with TensorFlow you can load it with:

```python
from transformers import  TFBertModel

model = TFBertModel.from_pretrained('dbmdz/bert-base-italian-xxl-cased') 
```

**Comment by wtfzambo** [comment]
yo, no worries, thanks for updating!
