### ISSUE TITLE
Reference paper for Italian BERT XXL?

### ISSUE THREAD

**Issue by maxzancanaro** [dbmdz/berts#51]
Hi DBMDZ team, this is not really an issue but I don't know how else I can get in touch with you. 
My team and I are using dbmdz/bert-base-italian-xxl-cased LLM on HuggingFace for a research project and we are now in the phase of writing a paper about our initial results. We would be really glad to cite your work, on which our is based, but I cannot find any reference paper. Can you point it out for me?
By the way, thanks very much for your amazing work.

M.

**Comment by stefan-it** [comment]
Hi @maxzancanaro ,

thanks for your interest in our model :hugs: 

Unfortunately, we do not have any related paper for the Italian BERT model(s), and we are not planing to write/publish a paper.

So the best way would be to add a reference to this repository and adding a link to the model on the Hugging Face Model Hub.

Best,

Stefan

**Comment by maxzancanaro** [comment]
ok ;->
