### ISSUE TITLE
Publishing of TF checkpoints for italian models

### ISSUE THREAD

**Issue by f-wole** [dbmdz/berts#6]
Thank you very much for generating these great Bert models in Italian! I've read that you plan to release the TF checkpoints, which I would greatly appreciate. May I ask when are you planning to release them? Thanks again

**Comment by stefan-it** [comment]
I'm currently preparing an archive with the checkpoints (for both cased and uncased models) now!

**Comment by stefan-it** [comment]
You can download both cased and uncased XXL models from:

```bash
$ wget https://schweter.eu/cloud/berts/bert-base-italian-xxl-cased.tar.gz
$ wget https://schweter.eu/cloud/berts/bert-base-italian-xxl-uncased.tar.gz
```

**Comment by f-wole** [comment]
thank you!!
