### ISSUE TITLE
License for models

### ISSUE THREAD

**Issue by MobiusLooper** [dbmdz/berts#9]
Hi!

First off, thanks for making and sharing these models.

Second, is there a license that can be applied to the pre-trained models themselves?

Thanks,
Josh

**Comment by stefan-it** [comment]
Hi @MobiusLooper ,

thanks for your interest! the license of the models will be MIT.

I'll update the main repo README soon :)

**Comment by MobiusLooper** [comment]
Thanks @stefan-it!
